name: Macos

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        c_compiler: [clang]
        include:
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
    steps:
      - uses: actions/checkout@v4

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.20
        with:
          create-symlink: true
          key: ${{ runner.os }}-${{ runner.arch }}-ccache

      - name: Install Dependencies
        run: |
          brew update
          brew install sdl3

      - name: Configure CMake
        if: ${{ runner.os != 'linux' }}
        run: >
          cmake -B build -G "Ninja Multi-Config"
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DBUILD_TESTING=ON

      - name: Build (Debug)
        run: cmake --build build --config Debug

      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Run Tests (Debug)
        working-directory: build
        run: ctest --build-config Debug

      - name: Run Tests (Release)
        working-directory: build
        run: ctest --build-config Release
